name       : python-libtmux
version    : 0.10.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/l/libtmux/libtmux-0.10.1.tar.gz : c8bc81499616ba899538704e419463a1c83ba7ca21e53b1efc6abbe98eb26b61
license    : MIT
component  : programming.python
summary    : Python API for tmux
description: |
    libtmux is the tool behind tmuxp, a tmux workspace manager in Python.
build      : |
    %python3_setup
install    : |
    %python3_install
