name       : python-libtmux
version    : 0.12.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/76/f9/81461ab705e3ae3736735e570ec59d5ea5d0d2f3022c00a4ac4b8fe6f0f5/libtmux-0.12.0.tar.gz : 881a38fb93fd5839ecdbcd2021e25dce4ea1d14431f46db894830c9a789af904
license    : MIT
component  : programming.python
summary    : Python API for tmux
description: |
    libtmux is the tool behind tmuxp, a tmux workspace manager in Python.
build      : |
    %python3_setup
install    : |
    %python3_install
