name       : python-libtmux
version    : 0.11.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/92/db/aa31905a3ba3d39890afb404528417aff74eb744222f03568e7a9d7e58b5/libtmux-0.11.0.tar.gz : d82cf391097eb69d784d889d482bb99284b984aa6225276a3dc1af8c1460dd3c
license    : MIT
component  : programming.python
summary    : Python API for tmux
description: |
    libtmux is the tool behind tmuxp, a tmux workspace manager in Python.
build      : |
    %python3_setup
install    : |
    %python3_install
