name       : python-libtmux
version    : 0.15.8
release    : 6
source     :
    - https://files.pythonhosted.org/packages/35/1f/c3dbf187f823e80cd22ce4bba3d52857b0c0e6775310c14ac5f99417635d/libtmux-0.15.8.tar.gz : cf352a645ebeaa5046ad0593cc01d691d77f8b3af1660327a6433cc6276ab796
license    : MIT
component  : programming.python
summary    : Python API for tmux
description: |
    libtmux is the tool behind tmuxp, a tmux workspace manager in Python.
build      : |
    %python3_setup
install    : |
    %python3_install
